BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE = yes
NKRO_ENABLE = yes
# UNICODE_ENABLE = yes
UNICODEMAP_ENABLE = yes
# KEY_LOCK_ENABLE = no
MOUSEKEY_ENABLE = no       # Mouse keys(+4700)

# COMMAND_ENABLE = no
